# Generated by Django 5.2 on 2025-06-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0003_reply_message_reply"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reply",
            options={"verbose_name_plural": "replies"},
        ),
        migrations.AlterField(
            model_name="message",
            name="reply",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="replies", to="notification.reply"
            ),
        ),
    ]
