# Generated by Django 5.2 on 2025-06-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0004_alter_reply_options_alter_message_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="reply",
            field=models.ManyToManyField(
                blank=True, related_name="replies", to="notification.reply"
            ),
        ),
    ]
