# Generated by Django 5.2 on 2025-06-26 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0005_alter_message_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reply",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message",
                to="notification.message",
            ),
        ),
        migrations.CreateModel(
            name="ReplyOfAReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_reply",
                    models.ForeignKey(
                        help_text="The reply you want to reply to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_replies",
                        to="notification.reply",
                    ),
                ),
                (
                    "derived_reply",
                    models.ForeignKey(
                        help_text="A reply to the base reply",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived_replies",
                        to="notification.reply",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "replies_of_reply",
            },
        ),
    ]
