# Generated by Django 5.2 on 2025-06-27 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0006_alter_reply_message_replyofareply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="reply",
        ),
        migrations.RemoveField(
            model_name="reply",
            name="from_user",
        ),
        migrations.RemoveField(
            model_name="reply",
            name="text",
        ),
        migrations.RemoveField(
            model_name="reply",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="reply",
            name="to_user",
        ),
        migrations.AddField(
            model_name="reply",
            name="message_reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_reply",
                to="notification.message",
            ),
        ),
        migrations.DeleteModel(
            name="ReplyOfAReply",
        ),
    ]
