# Generated by Django 5.2 on 2025-06-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0008_alter_message_options_message_reply_delete_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_reply",
            field=models.BooleanField(default=False),
        ),
    ]
