# Generated by Django 5.2 on 2025-06-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0010_alter_message_options_remove_message_is_reply_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
