# Generated by Django 5.2 on 2025-07-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0011_message_read"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat",
            options={"ordering": ["timestamp"]},
        ),
    ]
