# Generated by Django 5.2 on 2025-07-08 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("updates", "0005_viewer"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="updates.comment",
            ),
        ),
    ]
