# Generated by Django 5.2 on 2025-07-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("updates", "0006_comment_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(max_length=1200),
        ),
    ]
