# Generated by Django 5.2 on 2025-07-11 12:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("updates", "0007_alter_post_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="viewer",
            unique_together={("user", "post")},
        ),
    ]
