# Generated by Django 5.2 on 2025-07-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("updates", "0008_alter_viewer_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_reply",
            field=models.BooleanField(default=False),
        ),
    ]
